In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler ,OneHotEncoder , OrdinalEncoder , LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [2]:
df = pd.read_csv("social_media_screentime_mental_health_2026.csv")
df

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
0,P300000,33,Male,Student,Latin America,TikTok,8,3.2,172,Never,...,9,6,4,6,8,4,No,No,No,At-risk
1,P300001,23,Female,Full-time employed,Oceania,Instagram,8,4.5,38,Often,...,7,5,8,5,8,4,No,"Yes, failed",Yes,At-risk
2,P300002,56,Female,Full-time employed,Africa,Instagram,1,5.3,74,Every night,...,8,7,3,2,3,5,No,No,No,Moderate
3,P300003,13,Male,Student,Europe,YouTube,4,3.4,49,Sometimes,...,10,6,6,1,5,4,No,"Yes, failed",Yes,Moderate
4,P300004,36,Female,Student,Asia,LinkedIn,5,5.8,227,Never,...,4,6,8,7,9,3,Yes,"Yes, succeeded",No,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,P306995,30,Male,Part-time employed,Europe,Snapchat,4,3.6,74,Never,...,4,4,6,3,10,2,Yes,No,No,Good
6996,P306996,28,Male,Self-employed,North America,Facebook,3,5.0,104,Every night,...,8,1,7,6,7,1,No,"Yes, failed",No,Moderate
6997,P306997,26,Prefer not to say,Unemployed,Oceania,LinkedIn,3,1.2,25,Never,...,9,4,5,1,6,3,No,No,No,Good
6998,P306998,22,Female,Student,Europe,Snapchat,4,3.6,182,Sometimes,...,5,7,4,1,6,2,No,"Yes, failed",No,Good
6999,P306999,29,Male,Student,Asia,Facebook,1,5.8,14,Every night,...,5,7,4,9,6,3,No,No,Considering it,Moderate

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 25 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   participant_id                       7000 non-null   str
 1   age                                  7000 non-null   int64
 2   gender                               6930 non-null   str
 3   occupation                           7000 non-null   str
 4   region                               7000 non-null   str
 5   most_used_platform                   7000 non-null   str
 6   platforms_used_count                 7000 non-null   int64
 7   daily_screen_hours                   7000 non-null   float64
 8   daily_notifications                  7000 non-null   int64
 9   night_time_use                       7000 non-null   str
 10  minutes_to_first_check_after_waking  7000 non-null   int64
 11  primary_purpose                      7000 non-null   str
 12  avg_sleep_hours                      6895 non-null   float64
 13  anxiety_score_0to27                  7000 non-null   int64
 14  low_mood_score_0to27                 7000 non-null   int64
 15  life_satisfaction_1to10              7000 non-null   int64
 16  loneliness_1to10                     7000 non-null   int64
 17  self_esteem_1to10                    7000 non-null   int64
 18  fomo_1to10                           7000 non-null   int64
 19  social_comparison_1to10              7000 non-null   int64
 20  physical_activity_days_per_week      7000 non-null   int64
 21  uses_screen_time_limits              7000 non-null   str
 22  attempted_digital_detox              7000 non-null   str
 23  seeks_mental_health_support          7000 non-null   str
 24  wellbeing_band                       7000 non-null   str
dtypes: float64(2), int64(12), str(11)
memory usage: 1.9 MB

In [4]:
df.isnull().sum()

participant_id                           0
age                                      0
gender                                  70
occupation                               0
region                                   0
most_used_platform                       0
platforms_used_count                     0
daily_screen_hours                       0
daily_notifications                      0
night_time_use                           0
minutes_to_first_check_after_waking      0
primary_purpose                          0
avg_sleep_hours                        105
anxiety_score_0to27                      0
low_mood_score_0to27                     0
life_satisfaction_1to10                  0
loneliness_1to10                         0
self_esteem_1to10                        0
fomo_1to10                               0
social_comparison_1to10                  0
physical_activity_days_per_week          0
uses_screen_time_limits                  0
attempted_digital_detox                  0
seeks_mental_health_support              0
wellbeing_band                           0
dtype: int64

In [5]:
x = df.drop(columns=['participant_id','wellbeing_band'])
y = df['wellbeing_band']


le = LabelEncoder()
y = le.fit_transform(y)

In [6]:
x

,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,minutes_to_first_check_after_waking,...,low_mood_score_0to27,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support
0,33,Male,Student,Latin America,TikTok,8,3.2,172,Never,25,...,0,9,6,4,6,8,4,No,No,No
1,23,Female,Full-time employed,Oceania,Instagram,8,4.5,38,Often,26,...,2,7,5,8,5,8,4,No,"Yes, failed",Yes
2,56,Female,Full-time employed,Africa,Instagram,1,5.3,74,Every night,12,...,6,8,7,3,2,3,5,No,No,No
3,13,Male,Student,Europe,YouTube,4,3.4,49,Sometimes,21,...,0,10,6,6,1,5,4,No,"Yes, failed",Yes
4,36,Female,Student,Asia,LinkedIn,5,5.8,227,Never,19,...,1,4,6,8,7,9,3,Yes,"Yes, succeeded",No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,30,Male,Part-time employed,Europe,Snapchat,4,3.6,74,Never,7,...,8,4,4,6,3,10,2,Yes,No,No
6996,28,Male,Self-employed,North America,Facebook,3,5.0,104,Every night,48,...,0,8,1,7,6,7,1,No,"Yes, failed",No
6997,26,Prefer not to say,Unemployed,Oceania,LinkedIn,3,1.2,25,Never,6,...,9,9,4,5,1,6,3,No,No,No
6998,22,Female,Student,Europe,Snapchat,4,3.6,182,Sometimes,12,...,4,5,7,4,1,6,2,No,"Yes, failed",No
6999,29,Male,Student,Asia,Facebook,1,5.8,14,Every night,41,...,8,5,7,4,9,6,3,No,No,Considering it

In [7]:
y

array([0, 0, 2, ..., 1, 1, 2], shape=(7000,))

In [8]:
num_cols = x.select_dtypes(include=['int64', 'float64']).columns.tolist()
num_cols

['age',
 'platforms_used_count',
 'daily_screen_hours',
 'daily_notifications',
 'minutes_to_first_check_after_waking',
 'avg_sleep_hours',
 'anxiety_score_0to27',
 'low_mood_score_0to27',
 'life_satisfaction_1to10',
 'loneliness_1to10',
 'self_esteem_1to10',
 'fomo_1to10',
 'social_comparison_1to10',
 'physical_activity_days_per_week']

In [9]:
cat_cols = x.select_dtypes(include=['object']).columns.tolist()
cat_cols

C:\Users\SANIDHYA PRAJAPATI\AppData\Local\Temp\ipykernel_7156\1484901747.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = x.select_dtypes(include=['object']).columns.tolist()

['gender',
 'occupation',
 'region',
 'most_used_platform',
 'night_time_use',
 'primary_purpose',
 'uses_screen_time_limits',
 'attempted_digital_detox',
 'seeks_mental_health_support']

In [10]:
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

In [11]:
cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

In [12]:
preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols)
])

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [14]:
from sklearn.tree import DecisionTreeClassifier
decisiontree_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(random_state=42))
])

In [15]:
decisiontree_pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age',
                                                   'platforms_used_count',
                                                   'daily_screen_hours',
                                                   'daily_notifications',
                                                   'minutes_to_first_check_after_waking',
                                                   'avg_sleep_hours',
                                                   'anxiety_score_0to27',
                                                   'low_mood_score_0to27',
                                                   'life_satisfaction_1to10',
                                                   'lone...
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'occupation',
                                                   'region',
                                                   'most_used_platform',
                                                   'night_time_use',
                                                   'primary_purpose',
                                                   'uses_screen_time_limits',
                                                   'attempted_digital_detox',
                                                   'seeks_mental_health_support'])])),
                ('classifier', DecisionTreeClassifier(random_state=42))])

In [16]:
decision_pred = decisiontree_pipeline.predict(x_test)

In [17]:
print(f"Accuracy: {accuracy_score(y_test, decision_pred):.4f}\n")
print("Classification Report:")
print(classification_report(y_test, decision_pred))

Accuracy: 1.0000

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       188
           1       1.00      1.00      1.00       458
           2       1.00      1.00      1.00       754

    accuracy                           1.00      1400
   macro avg       1.00      1.00      1.00      1400
weighted avg       1.00      1.00      1.00      1400

In [18]:
from sklearn.ensemble import RandomForestClassifier
randomforest_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

In [19]:
randomforest_pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age',
                                                   'platforms_used_count',
                                                   'daily_screen_hours',
                                                   'daily_notifications',
                                                   'minutes_to_first_check_after_waking',
                                                   'avg_sleep_hours',
                                                   'anxiety_score_0to27',
                                                   'low_mood_score_0to27',
                                                   'life_satisfaction_1to10',
                                                   'lone...
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'occupation',
                                                   'region',
                                                   'most_used_platform',
                                                   'night_time_use',
                                                   'primary_purpose',
                                                   'uses_screen_time_limits',
                                                   'attempted_digital_detox',
                                                   'seeks_mental_health_support'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [20]:
random_pred = randomforest_pipeline.predict(x_test)

In [21]:
print(f"Accuracy: {accuracy_score(y_test, random_pred):.4f}\n")
print("Classification Report:")
print(classification_report(y_test, random_pred))

Accuracy: 0.9979

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       188
           1       1.00      1.00      1.00       458
           2       1.00      1.00      1.00       754

    accuracy                           1.00      1400
   macro avg       1.00      0.99      1.00      1400
weighted avg       1.00      1.00      1.00      1400

In [22]:
from xgboost import XGBClassifier

xgboost_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', XGBClassifier(random_state=42))
])

In [23]:
xgboost_pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age',
                                                   'platforms_used_count',
                                                   'daily_screen_hours',
                                                   'daily_notifications',
                                                   'minutes_to_first_check_after_waking',
                                                   'avg_sleep_hours',
                                                   'anxiety_score_0to27',
                                                   'low_mood_score_0to27',
                                                   'life_satisfaction_1to10',
                                                   'lone...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [24]:
xgboost_pred = xgboost_pipeline.predict(x_test)

In [25]:
print(f"Accuracy: {accuracy_score(y_test, xgboost_pred):.4f}\n")
print("Classification Report:")
print(classification_report(y_test, xgboost_pred))

Accuracy: 1.0000

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       188
           1       1.00      1.00      1.00       458
           2       1.00      1.00      1.00       754

    accuracy                           1.00      1400
   macro avg       1.00      1.00      1.00      1400
weighted avg       1.00      1.00      1.00      1400

In [26]:
total_participants = len(df)
avg_screen_time = df['daily_screen_hours'].mean()
avg_anxiety = df['anxiety_score_0to27'].mean()
at_risk_pct = (df['wellbeing_band'] == 'At-risk').mean() * 100

print(f"Total Participants: {total_participants}")
print(f"Avg Screen Time: {avg_screen_time:.2f} hrs")
print(f"Avg Anxiety Score: {avg_anxiety:.2f} / 27")
print(f"At-risk Percentage: {at_risk_pct:.1f}%")

Total Participants: 7000
Avg Screen Time: 3.30 hrs
Avg Anxiety Score: 11.38 / 27
At-risk Percentage: 13.9%

In [27]:
import joblib
joblib.dump(randomforest_pipeline, 'wellbeing_model.joblib')
joblib.dump(le, "label_encoder.joblib")
print('Model saved successfully as wellbeing_model.joblib')

Model saved successfully as wellbeing_model.joblib